version: '3'

services:
  postgresql:
    image: postgres
    container_name: first
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=first
      - POSTGRES_PASSWORD=first
      - POSTGRES_DATABASE=first
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-first
    ports:
      - '6379-6379'
